name: Release Branch Merge Source Check

permissions:
  contents: read
  pull-requests: read

on:
  pull_request:
    branches:
      - release/v*
  workflow_dispatch:

jobs:
  hotfix-branch:
    uses: NHSDigital/nhsapp-github-migration-tools/.github/workflows/hotfix_branch_name_check.yml@main
