name: Look for Jira Ticket link

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [opened]
  workflow_dispatch:

jobs:
  jira:
    if: "!startsWith(github.head_ref, 'dependabot/')"
    uses: NHSDigital/nhsapp-github-migration-tools/.github/workflows/jira_to_pr.yaml@main
    secrets:
      GH_TOKEN: ${{ github.token }}
      NHSAPP_JIRA_BOT_PAT: ${{ secrets.NHSAPP_JIRA_BOT_PAT }}
